// each const variable name = section#id
// Each key = the value for input type="checkbox"
// The selected languages values are saved to LS, but the Primary is saving the select option text value
// This is a bad file name
export const vars = {
  "JavaScript": [
    'let varName = value;',
    'const PHI = 1.618',
    'typeof',
    'console.log()',
    'null',
  ],
  "PHP": [
    '$varName = value;',
    'define("PHI", 1.618);',
    'gettype()',
    'var_dump()',
    'null',
  ],
  "Python": [
    'var_name = value',
    'PHI = 1.618',
    'type()',
    'print()',
    'None',
  ],
  "CSharp": [
    'var varName = value;',
    'const double PHI = 1.618;',
    'obj.GetType()',
    'Console.WriteLine(obj);',
    'null',
  ],
}

export const numbers = {
  "JavaScript": [
    'Infinity',
    'NaN',
    'Math.min(...nums)',
    'Math.max(...nums)',
    'Math.floor(x)',
    'Math.random()',
    'Math.sqrt(x)',
    'Math.pow(base, exp)',
    'parseInt(str, radix)',
    'parseFloat(string)',
    '% ** ++ --',
    '+= -= *= /=',
    'num++',
  ],
  "PHP": [
    'INF',
    '-',
    'min($a, $b)',
    'max($a, $b)',
    'floor($n)',
    'rand(min, max)',
    'sqrt($n)',
    'pow($a, $b)',
    'intval($str)',
    'floatval($str)',
    '% ** ++ --',
    '+= -= *= /=',
    '$num++',
  ],
  "Python": [
    'float("inf")',
    'float("nan")',
    'min(a, b)',
    'max(a, b)',
    'math.floor(n)',
    'random.random()',
    'import math | math.sqrt(n)',
    'pow(a, b) | a ** b',
    'int(str)',
    'float(str)',
    '% **',
    '+= -= *= /=',
    'num += 1',
  ],
  "CSharp": [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
}

export const strings = {
  "JavaScript": [
    '`Hello ${name}`',
    'str.length',
    'str[i]',
    'str + str2',
    '+=',
    'str.charCodeAt(i)',
    'str.startsWith(sub)',
    'str.endsWith(sub)',
    'str.includes(sub)',
    'str.indexOf(sub)',
    'str.slice(start, end)',
    'str.split(sep)',
    'str.repeat(count)',
    'str.replace(regex, replace)',
    'str.substring(start, end)',
    'str.toLowerCase()',
    'str.toUpperCase()',
    'str.trim()',
    'String(num)',
  ],
  "PHP": [
    '"Hello {$name}"',
    'strlen($str)',
    '$str[$i]',
    '$str . $str2',
    '.=',
    'ord($str[0])',
    'str_starts_with($str, $char)',
    'str_ends_with($str, $char)',
    'str_contains($str, $substr)',
    'strpos($str, $char)',
    'substr($str, start, +/-len)',
    'explode(sep, $str)',
    'str_repeat($str, $num)',
    'str_replace($char, "", $str)',
    'substr($str, $char)',
    'strtolower($str)',
    'strtoupper($str)',
    'trim($text)',
    'strval($num)',
  ],
  "Python": [
    'f"Hello {name}"',
    'len(string)',
    'string[index]',
    'string + string2',
    '+=',
    'ord(char)',
    'txt.startswith(char_or_substr)',
    'txt.endswith(char_or_substr)',
    'if char in string',
    'txt.find(char_or_substr)',
    'string[start:end]',
    'string.split(sep)',
    'str * num',
    'txt.replace(orig, replace)',
    'string[start:end]',
    'txt.lower()',
    'txt.upper()',
    'txt.strip()',
    'str(num)',
  ],
  "CSharp": [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
}

export const arrays = {
  "JavaScript": [
    'arr.length',
    'arr.length = 0',
    'arr2 = [...arr1]',
    'arr[i]',
    'arr.join(sep)',
    'arr1.concat(arr2)',
    'arr.filter(cb)',
    'arr.includes(item)',
    'arr.indexOf(item)',
    'arr.forEach((item, i))',
    'arr.map((item, i))',
    'arr.push(item)',
    'arr.unshift(item)',
    'arr.pop()',
    'arr.shift()',
    'arr.reduce(cb)',
    'arr.reverse()',
    'arr.sort()',
    'arr.slice(start, end)',
    'Array.from(iterable[, cb])',
    'arr.splice(i, 0, item)',
    'arr.splice(i, 1)',
    'arr.splice(i, 1, item)',
  ],
  "PHP": [
    'count($arr)',
    '$arr = [];',
    '$arr2 = [...$arr1];',
    '$arr[i]',
    'implode($sep, $arr)',
    'array_merge($arr1, $arr2)',
    'array_filter($arr, "cb")',
    'in_array($item, $arr)',
    'array_search($item, $arr)',
    'foreach ($arr as $val) {...}',
    'array_map("cb", $arr)',
    'array_push($arr, "vals")',
    'array_unshift($arr, "vals")',
    'array_pop($arr)',
    'array_shift($arr)',
    'array_reduce($arr, "cb")',
    'array_reverse($arr)',
    'sort($arr)',
    'array_slice($arr, start, len)',
    '-',
    'array_splice($arr, i, 0, item)',
    'array_splice($arr, i, 1)',
    'array_splice($arr, i, 1, item)',
  ],
  "Python": [
    'len(list_name)',
    'list1.clear()',
    'l2 = l1.copy(), l2 = l1[:]',
    'list1[i]',
    'sep.join(strings_list)',
    'list1 + list2',
    '[x for x in list1 if cb(x)]',
    'if item in list_name',
    'list1.index(item)',
    '-',
    '[cb(x) for x in list]',
    'list1.append(val)',
    'list1.insert(0, item)',
    'list1.pop(i)',
    'lis1t.pop(0)',
    '-',
    'list1.reverse()',
    'list1.sort()',
    'list1[start:end]',
    'list1(iterable)',
    'list1.insert(i, item)',
    'list1.pop(i)',
    'list1[i] = item',
  ],
  "CSharp": [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
}

export const objects = {
  "JavaScript": [
    'const obj = { key: val };',
    'obj.key | obj["key"]',
    'delete obj["key"];',
    'obj.hasOwnProperty(key);',
    'Object.entries(obj);',
    'Object.keys(obj);',
    'Object.values(obj);',
    'obj3 = {...obj1, ...obj2}',
  ],
  "PHP": [
    '$arr = ["key" => $val];',
    '$arr["key"];',
    'unset($arr["key"]);',
    'array_key_exists($key, $arr);',
    '-',
    'array_keys($arr);',
    'array_values($arr);',
    '$arr3 = $arr1 + $arr2;',
  ],
  "Python": [
    'dict1 = {"key": val}',
    'dict1["key"]',
    'dict1.pop("key")',
    'key in dict1',
    'dict1.items()',
    'dict1.keys()',
    'dict1.values()',
    'dict3 = {**dict1, **dict2}',
  ],
  "CSharp": [
    '',
    '',
    '',
    '',
    '',
    '',
    '',
    '',
  ],
}